name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    - name: Build and push Docker images
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
        repository: charlesgoh/github-actions-examples
        tags: latest
    
    - name: Notify Telegram
      # You may pin to the exact commit or the version.
      # uses: yanzay/notify-telegram@1025564e15f68b2fcddeba37b5bfaf4033c79448
      uses: yanzay/notify-telegram@v0.1.0
      with:
        # Chat to send: chat id or @channel_name
        chat: githubactions-examples
        # Telegram Bot token
        token: ${{ secrets.TELEGRAM_API_TOKEN }}
        # Job status
        status: Pushed new code
